version: "0.1"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
      POSTGRES_HOST: 'pulsar'
      POSTGRES_DB: 'pulsar'
      POSTGRES_USER: 'pulsar'
    ports:
      - "5436:5432"
    networks:
      - pulsar-network

networks:
  pulsar-network:
    driver: bridge
